/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.DefaultSchema;
import com.example.jooq.Keys;
import com.example.jooq.tables.Orders.OrdersPath;
import com.example.jooq.tables.records.CustomCakeOrdersRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomCakeOrders extends TableImpl<CustomCakeOrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>custom_cake_orders</code>
     */
    public static final CustomCakeOrders CUSTOM_CAKE_ORDERS = new CustomCakeOrders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomCakeOrdersRecord> getRecordType() {
        return CustomCakeOrdersRecord.class;
    }

    /**
     * The column <code>custom_cake_orders.id</code>.
     */
    public final TableField<CustomCakeOrdersRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>custom_cake_orders.base_cake_name</code>.
     */
    public final TableField<CustomCakeOrdersRecord, String> BASE_CAKE_NAME = createField(DSL.name("base_cake_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>custom_cake_orders.message</code>.
     */
    public final TableField<CustomCakeOrdersRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>custom_cake_orders.size</code>.
     */
    public final TableField<CustomCakeOrdersRecord, Double> SIZE = createField(DSL.name("size"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>custom_cake_orders.topping</code>.
     */
    public final TableField<CustomCakeOrdersRecord, String> TOPPING = createField(DSL.name("topping"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>custom_cake_orders.total_price</code>.
     */
    public final TableField<CustomCakeOrdersRecord, Double> TOTAL_PRICE = createField(DSL.name("total_price"), SQLDataType.DOUBLE.nullable(false), this, "");

    private CustomCakeOrders(Name alias, Table<CustomCakeOrdersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomCakeOrders(Name alias, Table<CustomCakeOrdersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>custom_cake_orders</code> table reference
     */
    public CustomCakeOrders(String alias) {
        this(DSL.name(alias), CUSTOM_CAKE_ORDERS);
    }

    /**
     * Create an aliased <code>custom_cake_orders</code> table reference
     */
    public CustomCakeOrders(Name alias) {
        this(alias, CUSTOM_CAKE_ORDERS);
    }

    /**
     * Create a <code>custom_cake_orders</code> table reference
     */
    public CustomCakeOrders() {
        this(DSL.name("custom_cake_orders"), null);
    }

    public <O extends Record> CustomCakeOrders(Table<O> path, ForeignKey<O, CustomCakeOrdersRecord> childPath, InverseForeignKey<O, CustomCakeOrdersRecord> parentPath) {
        super(path, childPath, parentPath, CUSTOM_CAKE_ORDERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CustomCakeOrdersPath extends CustomCakeOrders implements Path<CustomCakeOrdersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CustomCakeOrdersPath(Table<O> path, ForeignKey<O, CustomCakeOrdersRecord> childPath, InverseForeignKey<O, CustomCakeOrdersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CustomCakeOrdersPath(Name alias, Table<CustomCakeOrdersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CustomCakeOrdersPath as(String alias) {
            return new CustomCakeOrdersPath(DSL.name(alias), this);
        }

        @Override
        public CustomCakeOrdersPath as(Name alias) {
            return new CustomCakeOrdersPath(alias, this);
        }

        @Override
        public CustomCakeOrdersPath as(Table<?> alias) {
            return new CustomCakeOrdersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<CustomCakeOrdersRecord, Integer> getIdentity() {
        return (Identity<CustomCakeOrdersRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CustomCakeOrdersRecord> getPrimaryKey() {
        return Keys.KEY_CUSTOM_CAKE_ORDERS_PRIMARY;
    }

    @Override
    public List<ForeignKey<CustomCakeOrdersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK9REID2KALUBJQ8HK35EL758Q);
    }

    private transient OrdersPath _orders;

    /**
     * Get the implicit join path to the <code>defaultdb.orders</code> table.
     */
    public OrdersPath orders() {
        if (_orders == null)
            _orders = new OrdersPath(this, Keys.FK9REID2KALUBJQ8HK35EL758Q, null);

        return _orders;
    }

    @Override
    public CustomCakeOrders as(String alias) {
        return new CustomCakeOrders(DSL.name(alias), this);
    }

    @Override
    public CustomCakeOrders as(Name alias) {
        return new CustomCakeOrders(alias, this);
    }

    @Override
    public CustomCakeOrders as(Table<?> alias) {
        return new CustomCakeOrders(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomCakeOrders rename(String name) {
        return new CustomCakeOrders(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomCakeOrders rename(Name name) {
        return new CustomCakeOrders(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomCakeOrders rename(Table<?> name) {
        return new CustomCakeOrders(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomCakeOrders where(Condition condition) {
        return new CustomCakeOrders(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomCakeOrders where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomCakeOrders where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomCakeOrders where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomCakeOrders where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomCakeOrders where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomCakeOrders where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomCakeOrders where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomCakeOrders whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomCakeOrders whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
