/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.DefaultSchema;
import com.example.jooq.Keys;
import com.example.jooq.tables.Orders.OrdersPath;
import com.example.jooq.tables.records.StandardOrdersRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StandardOrders extends TableImpl<StandardOrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>standard_orders</code>
     */
    public static final StandardOrders STANDARD_ORDERS = new StandardOrders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StandardOrdersRecord> getRecordType() {
        return StandardOrdersRecord.class;
    }

    /**
     * The column <code>standard_orders.product_name</code>.
     */
    public final TableField<StandardOrdersRecord, String> PRODUCT_NAME = createField(DSL.name("product_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>standard_orders.quantity</code>.
     */
    public final TableField<StandardOrdersRecord, Integer> QUANTITY = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>standard_orders.unit_price</code>.
     */
    public final TableField<StandardOrdersRecord, Double> UNIT_PRICE = createField(DSL.name("unit_price"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>standard_orders.id</code>.
     */
    public final TableField<StandardOrdersRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    private StandardOrders(Name alias, Table<StandardOrdersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StandardOrders(Name alias, Table<StandardOrdersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>standard_orders</code> table reference
     */
    public StandardOrders(String alias) {
        this(DSL.name(alias), STANDARD_ORDERS);
    }

    /**
     * Create an aliased <code>standard_orders</code> table reference
     */
    public StandardOrders(Name alias) {
        this(alias, STANDARD_ORDERS);
    }

    /**
     * Create a <code>standard_orders</code> table reference
     */
    public StandardOrders() {
        this(DSL.name("standard_orders"), null);
    }

    public <O extends Record> StandardOrders(Table<O> path, ForeignKey<O, StandardOrdersRecord> childPath, InverseForeignKey<O, StandardOrdersRecord> parentPath) {
        super(path, childPath, parentPath, STANDARD_ORDERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StandardOrdersPath extends StandardOrders implements Path<StandardOrdersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StandardOrdersPath(Table<O> path, ForeignKey<O, StandardOrdersRecord> childPath, InverseForeignKey<O, StandardOrdersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StandardOrdersPath(Name alias, Table<StandardOrdersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StandardOrdersPath as(String alias) {
            return new StandardOrdersPath(DSL.name(alias), this);
        }

        @Override
        public StandardOrdersPath as(Name alias) {
            return new StandardOrdersPath(alias, this);
        }

        @Override
        public StandardOrdersPath as(Table<?> alias) {
            return new StandardOrdersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<StandardOrdersRecord> getPrimaryKey() {
        return Keys.KEY_STANDARD_ORDERS_PRIMARY;
    }

    @Override
    public List<ForeignKey<StandardOrdersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKUONMG9W0C6MQHT8WR6IMTA7Q);
    }

    private transient OrdersPath _orders;

    /**
     * Get the implicit join path to the <code>defaultdb.orders</code> table.
     */
    public OrdersPath orders() {
        if (_orders == null)
            _orders = new OrdersPath(this, Keys.FKUONMG9W0C6MQHT8WR6IMTA7Q, null);

        return _orders;
    }

    @Override
    public StandardOrders as(String alias) {
        return new StandardOrders(DSL.name(alias), this);
    }

    @Override
    public StandardOrders as(Name alias) {
        return new StandardOrders(alias, this);
    }

    @Override
    public StandardOrders as(Table<?> alias) {
        return new StandardOrders(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StandardOrders rename(String name) {
        return new StandardOrders(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StandardOrders rename(Name name) {
        return new StandardOrders(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StandardOrders rename(Table<?> name) {
        return new StandardOrders(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StandardOrders where(Condition condition) {
        return new StandardOrders(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StandardOrders where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StandardOrders where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StandardOrders where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StandardOrders where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StandardOrders where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StandardOrders where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StandardOrders where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StandardOrders whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StandardOrders whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
