/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.DefaultSchema;
import com.example.jooq.Keys;
import com.example.jooq.tables.TblCustomOrderInfo.TblCustomOrderInfoPath;
import com.example.jooq.tables.TblCustomShoppingCartInfo.TblCustomShoppingCartInfoPath;
import com.example.jooq.tables.records.TblModifierValuesRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblModifierValues extends TableImpl<TblModifierValuesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>tbl_modifier_values</code>
     */
    public static final TblModifierValues TBL_MODIFIER_VALUES = new TblModifierValues();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblModifierValuesRecord> getRecordType() {
        return TblModifierValuesRecord.class;
    }

    /**
     * The column <code>tbl_modifier_values.modifier_value_id</code>.
     */
    public final TableField<TblModifierValuesRecord, Integer> MODIFIER_VALUE_ID = createField(DSL.name("modifier_value_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>tbl_modifier_values.modifier_id</code>.
     */
    public final TableField<TblModifierValuesRecord, Integer> MODIFIER_ID = createField(DSL.name("modifier_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>tbl_modifier_values.modifier_value</code>.
     */
    public final TableField<TblModifierValuesRecord, String> MODIFIER_VALUE = createField(DSL.name("modifier_value"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>tbl_modifier_values.price_modifier</code>.
     */
    public final TableField<TblModifierValuesRecord, Double> PRICE_MODIFIER = createField(DSL.name("price_modifier"), SQLDataType.FLOAT, this, "");

    private TblModifierValues(Name alias, Table<TblModifierValuesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TblModifierValues(Name alias, Table<TblModifierValuesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>tbl_modifier_values</code> table reference
     */
    public TblModifierValues(String alias) {
        this(DSL.name(alias), TBL_MODIFIER_VALUES);
    }

    /**
     * Create an aliased <code>tbl_modifier_values</code> table reference
     */
    public TblModifierValues(Name alias) {
        this(alias, TBL_MODIFIER_VALUES);
    }

    /**
     * Create a <code>tbl_modifier_values</code> table reference
     */
    public TblModifierValues() {
        this(DSL.name("tbl_modifier_values"), null);
    }

    public <O extends Record> TblModifierValues(Table<O> path, ForeignKey<O, TblModifierValuesRecord> childPath, InverseForeignKey<O, TblModifierValuesRecord> parentPath) {
        super(path, childPath, parentPath, TBL_MODIFIER_VALUES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TblModifierValuesPath extends TblModifierValues implements Path<TblModifierValuesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TblModifierValuesPath(Table<O> path, ForeignKey<O, TblModifierValuesRecord> childPath, InverseForeignKey<O, TblModifierValuesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TblModifierValuesPath(Name alias, Table<TblModifierValuesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TblModifierValuesPath as(String alias) {
            return new TblModifierValuesPath(DSL.name(alias), this);
        }

        @Override
        public TblModifierValuesPath as(Name alias) {
            return new TblModifierValuesPath(alias, this);
        }

        @Override
        public TblModifierValuesPath as(Table<?> alias) {
            return new TblModifierValuesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<TblModifierValuesRecord> getPrimaryKey() {
        return Keys.KEY_TBL_MODIFIER_VALUES_PRIMARY;
    }

    private transient TblCustomOrderInfoPath _tblCustomOrderInfo;

    /**
     * Get the implicit to-many join path to the
     * <code>defaultdb.tbl_custom_order_info</code> table
     */
    public TblCustomOrderInfoPath tblCustomOrderInfo() {
        if (_tblCustomOrderInfo == null)
            _tblCustomOrderInfo = new TblCustomOrderInfoPath(this, null, Keys.FK_TBL_CUSTOM_ORDER_INFO_TBL_MODIFER_VALUES.getInverseKey());

        return _tblCustomOrderInfo;
    }

    private transient TblCustomShoppingCartInfoPath _tblCustomShoppingCartInfo;

    /**
     * Get the implicit to-many join path to the
     * <code>defaultdb.tbl_custom_shopping_cart_info</code> table
     */
    public TblCustomShoppingCartInfoPath tblCustomShoppingCartInfo() {
        if (_tblCustomShoppingCartInfo == null)
            _tblCustomShoppingCartInfo = new TblCustomShoppingCartInfoPath(this, null, Keys.FK_TBL_CUSTOM_ORDER_INFO_TBL_MODIFER_VALUES_1.getInverseKey());

        return _tblCustomShoppingCartInfo;
    }

    @Override
    public TblModifierValues as(String alias) {
        return new TblModifierValues(DSL.name(alias), this);
    }

    @Override
    public TblModifierValues as(Name alias) {
        return new TblModifierValues(alias, this);
    }

    @Override
    public TblModifierValues as(Table<?> alias) {
        return new TblModifierValues(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblModifierValues rename(String name) {
        return new TblModifierValues(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TblModifierValues rename(Name name) {
        return new TblModifierValues(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TblModifierValues rename(Table<?> name) {
        return new TblModifierValues(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TblModifierValues where(Condition condition) {
        return new TblModifierValues(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TblModifierValues where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TblModifierValues where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TblModifierValues where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TblModifierValues where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TblModifierValues where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TblModifierValues where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TblModifierValues where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TblModifierValues whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TblModifierValues whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
