/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.CustomCakeOrders;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomCakeOrdersRecord extends UpdatableRecordImpl<CustomCakeOrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>custom_cake_orders.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>custom_cake_orders.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>custom_cake_orders.base_cake_name</code>.
     */
    public void setBaseCakeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>custom_cake_orders.base_cake_name</code>.
     */
    public String getBaseCakeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>custom_cake_orders.message</code>.
     */
    public void setMessage(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>custom_cake_orders.message</code>.
     */
    public String getMessage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>custom_cake_orders.size</code>.
     */
    public void setSize(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>custom_cake_orders.size</code>.
     */
    public Double getSize() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>custom_cake_orders.topping</code>.
     */
    public void setTopping(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>custom_cake_orders.topping</code>.
     */
    public String getTopping() {
        return (String) get(4);
    }

    /**
     * Setter for <code>custom_cake_orders.total_price</code>.
     */
    public void setTotalPrice(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>custom_cake_orders.total_price</code>.
     */
    public Double getTotalPrice() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomCakeOrdersRecord
     */
    public CustomCakeOrdersRecord() {
        super(CustomCakeOrders.CUSTOM_CAKE_ORDERS);
    }

    /**
     * Create a detached, initialised CustomCakeOrdersRecord
     */
    public CustomCakeOrdersRecord(Integer id, String baseCakeName, String message, Double size, String topping, Double totalPrice) {
        super(CustomCakeOrders.CUSTOM_CAKE_ORDERS);

        setId(id);
        setBaseCakeName(baseCakeName);
        setMessage(message);
        setSize(size);
        setTopping(topping);
        setTotalPrice(totalPrice);
        resetChangedOnNotNull();
    }
}
