/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.Orders;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>orders.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>orders.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>orders.customer_name</code>.
     */
    public void setCustomerName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>orders.customer_name</code>.
     */
    public String getCustomerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>orders.order_date</code>.
     */
    public void setOrderDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>orders.order_date</code>.
     */
    public LocalDateTime getOrderDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>orders.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>orders.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>orders.total_price</code>.
     */
    public void setTotalPrice(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>orders.total_price</code>.
     */
    public Double getTotalPrice() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Integer id, String customerName, LocalDateTime orderDate, String status, Double totalPrice) {
        super(Orders.ORDERS);

        setId(id);
        setCustomerName(customerName);
        setOrderDate(orderDate);
        setStatus(status);
        setTotalPrice(totalPrice);
        resetChangedOnNotNull();
    }
}
