/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.StandardOrders;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StandardOrdersRecord extends UpdatableRecordImpl<StandardOrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>standard_orders.product_name</code>.
     */
    public void setProductName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>standard_orders.product_name</code>.
     */
    public String getProductName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>standard_orders.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>standard_orders.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>standard_orders.unit_price</code>.
     */
    public void setUnitPrice(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>standard_orders.unit_price</code>.
     */
    public Double getUnitPrice() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>standard_orders.id</code>.
     */
    public void setId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>standard_orders.id</code>.
     */
    public Integer getId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StandardOrdersRecord
     */
    public StandardOrdersRecord() {
        super(StandardOrders.STANDARD_ORDERS);
    }

    /**
     * Create a detached, initialised StandardOrdersRecord
     */
    public StandardOrdersRecord(String productName, Integer quantity, Double unitPrice, Integer id) {
        super(StandardOrders.STANDARD_ORDERS);

        setProductName(productName);
        setQuantity(quantity);
        setUnitPrice(unitPrice);
        setId(id);
        resetChangedOnNotNull();
    }
}
