/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.TblCustomOrderInfo;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblCustomOrderInfoRecord extends UpdatableRecordImpl<TblCustomOrderInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tbl_custom_order_info.custom_order_id</code>.
     */
    public void setCustomOrderId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tbl_custom_order_info.custom_order_id</code>.
     */
    public Integer getCustomOrderId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tbl_custom_order_info.order_id</code>.
     */
    public void setOrderId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>tbl_custom_order_info.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>tbl_custom_order_info.modifier_id</code>.
     */
    public void setModifierId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>tbl_custom_order_info.modifier_id</code>.
     */
    public Integer getModifierId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>tbl_custom_order_info.modifier_value_id</code>.
     */
    public void setModifierValueId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>tbl_custom_order_info.modifier_value_id</code>.
     */
    public Integer getModifierValueId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblCustomOrderInfoRecord
     */
    public TblCustomOrderInfoRecord() {
        super(TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO);
    }

    /**
     * Create a detached, initialised TblCustomOrderInfoRecord
     */
    public TblCustomOrderInfoRecord(Integer customOrderId, Integer orderId, Integer modifierId, Integer modifierValueId) {
        super(TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO);

        setCustomOrderId(customOrderId);
        setOrderId(orderId);
        setModifierId(modifierId);
        setModifierValueId(modifierValueId);
        resetChangedOnNotNull();
    }
}
