/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.TblModifierValues;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblModifierValuesRecord extends UpdatableRecordImpl<TblModifierValuesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tbl_modifier_values.modifier_value_id</code>.
     */
    public void setModifierValueId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tbl_modifier_values.modifier_value_id</code>.
     */
    public Integer getModifierValueId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tbl_modifier_values.modifier_id</code>.
     */
    public void setModifierId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>tbl_modifier_values.modifier_id</code>.
     */
    public Integer getModifierId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>tbl_modifier_values.modifier_value</code>.
     */
    public void setModifierValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tbl_modifier_values.modifier_value</code>.
     */
    public String getModifierValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tbl_modifier_values.price_modifier</code>.
     */
    public void setPriceModifier(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>tbl_modifier_values.price_modifier</code>.
     */
    public Double getPriceModifier() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblModifierValuesRecord
     */
    public TblModifierValuesRecord() {
        super(TblModifierValues.TBL_MODIFIER_VALUES);
    }

    /**
     * Create a detached, initialised TblModifierValuesRecord
     */
    public TblModifierValuesRecord(Integer modifierValueId, Integer modifierId, String modifierValue, Double priceModifier) {
        super(TblModifierValues.TBL_MODIFIER_VALUES);

        setModifierValueId(modifierValueId);
        setModifierId(modifierId);
        setModifierValue(modifierValue);
        setPriceModifier(priceModifier);
        resetChangedOnNotNull();
    }
}
