/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.TblProdCategories;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblProdCategoriesRecord extends UpdatableRecordImpl<TblProdCategoriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tbl_prod_categories.categeory_id</code>.
     */
    public void setCategeoryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tbl_prod_categories.categeory_id</code>.
     */
    public Integer getCategeoryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tbl_prod_categories.category_name</code>.
     */
    public void setCategoryName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tbl_prod_categories.category_name</code>.
     */
    public String getCategoryName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblProdCategoriesRecord
     */
    public TblProdCategoriesRecord() {
        super(TblProdCategories.TBL_PROD_CATEGORIES);
    }

    /**
     * Create a detached, initialised TblProdCategoriesRecord
     */
    public TblProdCategoriesRecord(Integer categeoryId, String categoryName) {
        super(TblProdCategories.TBL_PROD_CATEGORIES);

        setCategeoryId(categeoryId);
        setCategoryName(categoryName);
        resetChangedOnNotNull();
    }
}
