/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.TblShoppingCartItems;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblShoppingCartItemsRecord extends UpdatableRecordImpl<TblShoppingCartItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tbl_shopping_cart_items.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tbl_shopping_cart_items.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tbl_shopping_cart_items.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>tbl_shopping_cart_items.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>tbl_shopping_cart_items.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>tbl_shopping_cart_items.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>tbl_shopping_cart_items.quantity_ordered</code>.
     */
    public void setQuantityOrdered(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>tbl_shopping_cart_items.quantity_ordered</code>.
     */
    public Integer getQuantityOrdered() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblShoppingCartItemsRecord
     */
    public TblShoppingCartItemsRecord() {
        super(TblShoppingCartItems.TBL_SHOPPING_CART_ITEMS);
    }

    /**
     * Create a detached, initialised TblShoppingCartItemsRecord
     */
    public TblShoppingCartItemsRecord(Integer id, Integer userId, Integer productId, Integer quantityOrdered) {
        super(TblShoppingCartItems.TBL_SHOPPING_CART_ITEMS);

        setId(id);
        setUserId(userId);
        setProductId(productId);
        setQuantityOrdered(quantityOrdered);
        resetChangedOnNotNull();
    }
}
