/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.TblUsers;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUsersRecord extends UpdatableRecordImpl<TblUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tbl_users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tbl_users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tbl_users.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tbl_users.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tbl_users.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tbl_users.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tbl_users.employee</code>.
     */
    public void setEmployee(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>tbl_users.employee</code>.
     */
    public Boolean getEmployee() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>tbl_users.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tbl_users.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tbl_users.user_address</code>.
     */
    public void setUserAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tbl_users.user_address</code>.
     */
    public String getUserAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tbl_users.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>tbl_users.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblUsersRecord
     */
    public TblUsersRecord() {
        super(TblUsers.TBL_USERS);
    }

    /**
     * Create a detached, initialised TblUsersRecord
     */
    public TblUsersRecord(Integer id, String username, String password, Boolean employee, String email, String userAddress, String phoneNumber) {
        super(TblUsers.TBL_USERS);

        setId(id);
        setUsername(username);
        setPassword(password);
        setEmployee(employee);
        setEmail(email);
        setUserAddress(userAddress);
        setPhoneNumber(phoneNumber);
        resetChangedOnNotNull();
    }
}
