/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.CustomCakeOrders;
import com.example.jooq.tables.Orders;
import com.example.jooq.tables.StandardOrders;
import com.example.jooq.tables.TblCakeOrders;
import com.example.jooq.tables.TblCustomModifiers;
import com.example.jooq.tables.TblCustomOrderInfo;
import com.example.jooq.tables.TblCustomShoppingCartInfo;
import com.example.jooq.tables.TblModifierValues;
import com.example.jooq.tables.TblProdCategories;
import com.example.jooq.tables.TblProducts;
import com.example.jooq.tables.TblShoppingCartItems;
import com.example.jooq.tables.TblUsers;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>custom_cake_orders</code>.
     */
    public final CustomCakeOrders CUSTOM_CAKE_ORDERS = CustomCakeOrders.CUSTOM_CAKE_ORDERS;

    /**
     * The table <code>orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>standard_orders</code>.
     */
    public final StandardOrders STANDARD_ORDERS = StandardOrders.STANDARD_ORDERS;

    /**
     * The table <code>tbl_cake_orders</code>.
     */
    public final TblCakeOrders TBL_CAKE_ORDERS = TblCakeOrders.TBL_CAKE_ORDERS;

    /**
     * The table <code>tbl_custom_modifiers</code>.
     */
    public final TblCustomModifiers TBL_CUSTOM_MODIFIERS = TblCustomModifiers.TBL_CUSTOM_MODIFIERS;

    /**
     * The table <code>tbl_custom_order_info</code>.
     */
    public final TblCustomOrderInfo TBL_CUSTOM_ORDER_INFO = TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO;

    /**
     * The table <code>tbl_custom_shopping_cart_info</code>.
     */
    public final TblCustomShoppingCartInfo TBL_CUSTOM_SHOPPING_CART_INFO = TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO;

    /**
     * The table <code>tbl_modifier_values</code>.
     */
    public final TblModifierValues TBL_MODIFIER_VALUES = TblModifierValues.TBL_MODIFIER_VALUES;

    /**
     * The table <code>tbl_prod_categories</code>.
     */
    public final TblProdCategories TBL_PROD_CATEGORIES = TblProdCategories.TBL_PROD_CATEGORIES;

    /**
     * The table <code>tbl_products</code>.
     */
    public final TblProducts TBL_PRODUCTS = TblProducts.TBL_PRODUCTS;

    /**
     * The table <code>tbl_shopping_cart_items</code>.
     */
    public final TblShoppingCartItems TBL_SHOPPING_CART_ITEMS = TblShoppingCartItems.TBL_SHOPPING_CART_ITEMS;

    /**
     * The table <code>tbl_users</code>.
     */
    public final TblUsers TBL_USERS = TblUsers.TBL_USERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CustomCakeOrders.CUSTOM_CAKE_ORDERS,
            Orders.ORDERS,
            StandardOrders.STANDARD_ORDERS,
            TblCakeOrders.TBL_CAKE_ORDERS,
            TblCustomModifiers.TBL_CUSTOM_MODIFIERS,
            TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO,
            TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO,
            TblModifierValues.TBL_MODIFIER_VALUES,
            TblProdCategories.TBL_PROD_CATEGORIES,
            TblProducts.TBL_PRODUCTS,
            TblShoppingCartItems.TBL_SHOPPING_CART_ITEMS,
            TblUsers.TBL_USERS
        );
    }
}
