/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.TblCustomOrderInfo;
import com.example.jooq.tables.TblCustomShoppingCartInfo;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TBL_CUSTOM_SHOPPING_CART_INFO_FK_TBL_CUSTOM_ORDER_INFO_TBL_CUSTOM_MODIFIERS_0 = Internal.createIndex(DSL.name("fk_tbl_custom_order_info_tbl_custom_modifiers_0"), TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO, new OrderField[] { TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO.MODIFIER_ID }, false);
    public static final Index TBL_CUSTOM_ORDER_INFO_IDX_TBL_CUSTOM_ORDER_INFO_MODIFIER_VALUE_ID = Internal.createIndex(DSL.name("idx_tbl_custom_order_info_modifier_value_id"), TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO, new OrderField[] { TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO.MODIFIER_VALUE_ID }, false);
    public static final Index TBL_CUSTOM_SHOPPING_CART_INFO_IDX_TBL_CUSTOM_SHOPPING_CART_INFO_MODIFIER_VALUE_ID = Internal.createIndex(DSL.name("idx_tbl_custom_shopping_cart_info_modifier_value_id"), TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO, new OrderField[] { TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO.MODIFIER_VALUE_ID }, false);
}
