/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.CustomCakeOrders;
import com.example.jooq.tables.Orders;
import com.example.jooq.tables.StandardOrders;
import com.example.jooq.tables.TblCakeOrders;
import com.example.jooq.tables.TblCustomModifiers;
import com.example.jooq.tables.TblCustomOrderInfo;
import com.example.jooq.tables.TblCustomShoppingCartInfo;
import com.example.jooq.tables.TblModifierValues;
import com.example.jooq.tables.TblProdCategories;
import com.example.jooq.tables.TblProducts;
import com.example.jooq.tables.TblShoppingCartItems;
import com.example.jooq.tables.TblUsers;
import com.example.jooq.tables.records.CustomCakeOrdersRecord;
import com.example.jooq.tables.records.OrdersRecord;
import com.example.jooq.tables.records.StandardOrdersRecord;
import com.example.jooq.tables.records.TblCakeOrdersRecord;
import com.example.jooq.tables.records.TblCustomModifiersRecord;
import com.example.jooq.tables.records.TblCustomOrderInfoRecord;
import com.example.jooq.tables.records.TblCustomShoppingCartInfoRecord;
import com.example.jooq.tables.records.TblModifierValuesRecord;
import com.example.jooq.tables.records.TblProdCategoriesRecord;
import com.example.jooq.tables.records.TblProductsRecord;
import com.example.jooq.tables.records.TblShoppingCartItemsRecord;
import com.example.jooq.tables.records.TblUsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomCakeOrdersRecord> KEY_CUSTOM_CAKE_ORDERS_PRIMARY = Internal.createUniqueKey(CustomCakeOrders.CUSTOM_CAKE_ORDERS, DSL.name("KEY_custom_cake_orders_PRIMARY"), new TableField[] { CustomCakeOrders.CUSTOM_CAKE_ORDERS.ID }, true);
    public static final UniqueKey<OrdersRecord> KEY_ORDERS_PRIMARY = Internal.createUniqueKey(Orders.ORDERS, DSL.name("KEY_orders_PRIMARY"), new TableField[] { Orders.ORDERS.ID }, true);
    public static final UniqueKey<StandardOrdersRecord> KEY_STANDARD_ORDERS_PRIMARY = Internal.createUniqueKey(StandardOrders.STANDARD_ORDERS, DSL.name("KEY_standard_orders_PRIMARY"), new TableField[] { StandardOrders.STANDARD_ORDERS.ID }, true);
    public static final UniqueKey<TblCakeOrdersRecord> KEY_TBL_CAKE_ORDERS_PRIMARY = Internal.createUniqueKey(TblCakeOrders.TBL_CAKE_ORDERS, DSL.name("KEY_tbl_cake_orders_PRIMARY"), new TableField[] { TblCakeOrders.TBL_CAKE_ORDERS.ORDER_ID }, true);
    public static final UniqueKey<TblCustomModifiersRecord> KEY_TBL_CUSTOM_MODIFIERS_PRIMARY = Internal.createUniqueKey(TblCustomModifiers.TBL_CUSTOM_MODIFIERS, DSL.name("KEY_tbl_custom_modifiers_PRIMARY"), new TableField[] { TblCustomModifiers.TBL_CUSTOM_MODIFIERS.MODIFIER_ID }, true);
    public static final UniqueKey<TblCustomOrderInfoRecord> KEY_TBL_CUSTOM_ORDER_INFO_PRIMARY = Internal.createUniqueKey(TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO, DSL.name("KEY_tbl_custom_order_info_PRIMARY"), new TableField[] { TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO.CUSTOM_ORDER_ID }, true);
    public static final UniqueKey<TblCustomShoppingCartInfoRecord> KEY_TBL_CUSTOM_SHOPPING_CART_INFO_PRIMARY = Internal.createUniqueKey(TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO, DSL.name("KEY_tbl_custom_shopping_cart_info_PRIMARY"), new TableField[] { TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO.CUSTOM_ORDER_ID }, true);
    public static final UniqueKey<TblCustomShoppingCartInfoRecord> KEY_TBL_CUSTOM_SHOPPING_CART_INFO_UNQ_TBL_CUSTOM_ORDER_INFO_ORDER_ID_0 = Internal.createUniqueKey(TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO, DSL.name("KEY_tbl_custom_shopping_cart_info_unq_tbl_custom_order_info_order_id_0"), new TableField[] { TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO.SHOPPING_CART_ITEM_ID }, true);
    public static final UniqueKey<TblModifierValuesRecord> KEY_TBL_MODIFIER_VALUES_PRIMARY = Internal.createUniqueKey(TblModifierValues.TBL_MODIFIER_VALUES, DSL.name("KEY_tbl_modifier_values_PRIMARY"), new TableField[] { TblModifierValues.TBL_MODIFIER_VALUES.MODIFIER_VALUE_ID }, true);
    public static final UniqueKey<TblProdCategoriesRecord> KEY_TBL_PROD_CATEGORIES_NO_DUPLICATE_CATEGORY_NAMES = Internal.createUniqueKey(TblProdCategories.TBL_PROD_CATEGORIES, DSL.name("KEY_tbl_prod_categories_no_duplicate_category_names"), new TableField[] { TblProdCategories.TBL_PROD_CATEGORIES.CATEGORY_NAME }, true);
    public static final UniqueKey<TblProdCategoriesRecord> KEY_TBL_PROD_CATEGORIES_PRIMARY = Internal.createUniqueKey(TblProdCategories.TBL_PROD_CATEGORIES, DSL.name("KEY_tbl_prod_categories_PRIMARY"), new TableField[] { TblProdCategories.TBL_PROD_CATEGORIES.CATEGEORY_ID }, true);
    public static final UniqueKey<TblProductsRecord> KEY_TBL_PRODUCTS_PRIMARY = Internal.createUniqueKey(TblProducts.TBL_PRODUCTS, DSL.name("KEY_tbl_products_PRIMARY"), new TableField[] { TblProducts.TBL_PRODUCTS.PRODUCT_ID }, true);
    public static final UniqueKey<TblShoppingCartItemsRecord> KEY_TBL_SHOPPING_CART_ITEMS_PRIMARY = Internal.createUniqueKey(TblShoppingCartItems.TBL_SHOPPING_CART_ITEMS, DSL.name("KEY_tbl_shopping_cart_items_PRIMARY"), new TableField[] { TblShoppingCartItems.TBL_SHOPPING_CART_ITEMS.ID }, true);
    public static final UniqueKey<TblUsersRecord> KEY_TBL_USERS_CONS = Internal.createUniqueKey(TblUsers.TBL_USERS, DSL.name("KEY_tbl_users_cons"), new TableField[] { TblUsers.TBL_USERS.USERNAME }, true);
    public static final UniqueKey<TblUsersRecord> KEY_TBL_USERS_NO_DUPLICATE_EMAILS = Internal.createUniqueKey(TblUsers.TBL_USERS, DSL.name("KEY_tbl_users_no_duplicate_emails"), new TableField[] { TblUsers.TBL_USERS.EMAIL }, true);
    public static final UniqueKey<TblUsersRecord> KEY_TBL_USERS_PRIMARY = Internal.createUniqueKey(TblUsers.TBL_USERS, DSL.name("KEY_tbl_users_PRIMARY"), new TableField[] { TblUsers.TBL_USERS.ID }, true);
    public static final UniqueKey<TblUsersRecord> KEY_TBL_USERS_UQ_USERNAME = Internal.createUniqueKey(TblUsers.TBL_USERS, DSL.name("KEY_tbl_users_UQ_Username"), new TableField[] { TblUsers.TBL_USERS.USERNAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CustomCakeOrdersRecord, OrdersRecord> FK9REID2KALUBJQ8HK35EL758Q = Internal.createForeignKey(CustomCakeOrders.CUSTOM_CAKE_ORDERS, DSL.name("FK9reid2kalubjq8hk35el758q"), new TableField[] { CustomCakeOrders.CUSTOM_CAKE_ORDERS.ID }, Keys.KEY_ORDERS_PRIMARY, new TableField[] { Orders.ORDERS.ID }, true);
    public static final ForeignKey<StandardOrdersRecord, OrdersRecord> FKUONMG9W0C6MQHT8WR6IMTA7Q = Internal.createForeignKey(StandardOrders.STANDARD_ORDERS, DSL.name("FKuonmg9w0c6mqht8wr6imta7q"), new TableField[] { StandardOrders.STANDARD_ORDERS.ID }, Keys.KEY_ORDERS_PRIMARY, new TableField[] { Orders.ORDERS.ID }, true);
    public static final ForeignKey<TblCakeOrdersRecord, TblProductsRecord> FK_TBL_CAKE_ORDERS_TBL_PRODUCTS = Internal.createForeignKey(TblCakeOrders.TBL_CAKE_ORDERS, DSL.name("fk_tbl_cake_orders_tbl_products"), new TableField[] { TblCakeOrders.TBL_CAKE_ORDERS.PRODUCT_ID }, Keys.KEY_TBL_PRODUCTS_PRIMARY, new TableField[] { TblProducts.TBL_PRODUCTS.PRODUCT_ID }, true);
    public static final ForeignKey<TblCakeOrdersRecord, TblUsersRecord> FK_TBL_CAKE_ORDERS_TBL_USERS_0 = Internal.createForeignKey(TblCakeOrders.TBL_CAKE_ORDERS, DSL.name("fk_tbl_cake_orders_tbl_users_0"), new TableField[] { TblCakeOrders.TBL_CAKE_ORDERS.CUSTOMER_ID }, Keys.KEY_TBL_USERS_PRIMARY, new TableField[] { TblUsers.TBL_USERS.ID }, true);
    public static final ForeignKey<TblCustomOrderInfoRecord, TblCakeOrdersRecord> FK_TBL_CUSTOM_ORDER_INFO_TBL_CAKE_ORDERS = Internal.createForeignKey(TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO, DSL.name("fk_tbl_custom_order_info_tbl_cake_orders"), new TableField[] { TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO.CUSTOM_ORDER_ID }, Keys.KEY_TBL_CAKE_ORDERS_PRIMARY, new TableField[] { TblCakeOrders.TBL_CAKE_ORDERS.ORDER_ID }, true);
    public static final ForeignKey<TblCustomOrderInfoRecord, TblCustomModifiersRecord> FK_TBL_CUSTOM_ORDER_INFO_TBL_CUSTOM_MODIFIERS = Internal.createForeignKey(TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO, DSL.name("fk_tbl_custom_order_info_tbl_custom_modifiers"), new TableField[] { TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO.MODIFIER_ID }, Keys.KEY_TBL_CUSTOM_MODIFIERS_PRIMARY, new TableField[] { TblCustomModifiers.TBL_CUSTOM_MODIFIERS.MODIFIER_ID }, true);
    public static final ForeignKey<TblCustomOrderInfoRecord, TblModifierValuesRecord> FK_TBL_CUSTOM_ORDER_INFO_TBL_MODIFER_VALUES = Internal.createForeignKey(TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO, DSL.name("fk_tbl_custom_order_info_tbl_modifer_values"), new TableField[] { TblCustomOrderInfo.TBL_CUSTOM_ORDER_INFO.MODIFIER_VALUE_ID }, Keys.KEY_TBL_MODIFIER_VALUES_PRIMARY, new TableField[] { TblModifierValues.TBL_MODIFIER_VALUES.MODIFIER_VALUE_ID }, true);
    public static final ForeignKey<TblCustomShoppingCartInfoRecord, TblCustomModifiersRecord> FK_TBL_CUSTOM_ORDER_INFO_TBL_CUSTOM_MODIFIERS_1 = Internal.createForeignKey(TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO, DSL.name("fk_tbl_custom_order_info_tbl_custom_modifiers_1"), new TableField[] { TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO.MODIFIER_ID }, Keys.KEY_TBL_CUSTOM_MODIFIERS_PRIMARY, new TableField[] { TblCustomModifiers.TBL_CUSTOM_MODIFIERS.MODIFIER_ID }, true);
    public static final ForeignKey<TblCustomShoppingCartInfoRecord, TblModifierValuesRecord> FK_TBL_CUSTOM_ORDER_INFO_TBL_MODIFER_VALUES_1 = Internal.createForeignKey(TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO, DSL.name("fk_tbl_custom_order_info_tbl_modifer_values_1"), new TableField[] { TblCustomShoppingCartInfo.TBL_CUSTOM_SHOPPING_CART_INFO.MODIFIER_VALUE_ID }, Keys.KEY_TBL_MODIFIER_VALUES_PRIMARY, new TableField[] { TblModifierValues.TBL_MODIFIER_VALUES.MODIFIER_VALUE_ID }, true);
    public static final ForeignKey<TblProductsRecord, TblProdCategoriesRecord> FK_TBL_PRODUCTS_TBL_PROD_CATEGORIES = Internal.createForeignKey(TblProducts.TBL_PRODUCTS, DSL.name("fk_tbl_products_tbl_prod_categories"), new TableField[] { TblProducts.TBL_PRODUCTS.PRODUCT_CATEGORY }, Keys.KEY_TBL_PROD_CATEGORIES_PRIMARY, new TableField[] { TblProdCategories.TBL_PROD_CATEGORIES.CATEGEORY_ID }, true);
    public static final ForeignKey<TblShoppingCartItemsRecord, TblProductsRecord> FK_TBL_SHOPPING_CART_ITEMS_TBL_PRODUCTS = Internal.createForeignKey(TblShoppingCartItems.TBL_SHOPPING_CART_ITEMS, DSL.name("fk_tbl_shopping_cart_items_tbl_products"), new TableField[] { TblShoppingCartItems.TBL_SHOPPING_CART_ITEMS.PRODUCT_ID }, Keys.KEY_TBL_PRODUCTS_PRIMARY, new TableField[] { TblProducts.TBL_PRODUCTS.PRODUCT_ID }, true);
    public static final ForeignKey<TblShoppingCartItemsRecord, TblUsersRecord> FK_TBL_SHOPPING_CART_ITEMS_TBL_USERS = Internal.createForeignKey(TblShoppingCartItems.TBL_SHOPPING_CART_ITEMS, DSL.name("fk_tbl_shopping_cart_items_tbl_users"), new TableField[] { TblShoppingCartItems.TBL_SHOPPING_CART_ITEMS.USER_ID }, Keys.KEY_TBL_USERS_PRIMARY, new TableField[] { TblUsers.TBL_USERS.ID }, true);
}
